# Generated by Django 4.1.7 on 2023-03-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlle', models.CharField(max_length=200)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
    ]
