# Generated by Django 4.1.7 on 2023-03-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_picture',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
